// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	douyinmessage "douyin/kitex_gen/douyinmessage"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ChatRecord(ctx context.Context, req *douyinmessage.ChatRecordRequest, callOptions ...callopt.Option) (r *douyinmessage.ChatRecordResponse, err error)
	SendMessage(ctx context.Context, req *douyinmessage.SendMessageRequest, callOptions ...callopt.Option) (r *douyinmessage.SendMessageResponse, err error)
	GetFirstMessages(ctx context.Context, req *douyinmessage.GetFirstMessagesRequest, callOptions ...callopt.Option) (r *douyinmessage.GetFirstMessagesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) ChatRecord(ctx context.Context, req *douyinmessage.ChatRecordRequest, callOptions ...callopt.Option) (r *douyinmessage.ChatRecordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChatRecord(ctx, req)
}

func (p *kMessageServiceClient) SendMessage(ctx context.Context, req *douyinmessage.SendMessageRequest, callOptions ...callopt.Option) (r *douyinmessage.SendMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, req)
}

func (p *kMessageServiceClient) GetFirstMessages(ctx context.Context, req *douyinmessage.GetFirstMessagesRequest, callOptions ...callopt.Option) (r *douyinmessage.GetFirstMessagesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFirstMessages(ctx, req)
}
