// Code generated by Kitex v0.4.4. DO NOT EDIT.

package commentservice

import (
	"context"
	douyincomment "douyin/kitex_gen/douyincomment"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return commentServiceServiceInfo
}

var commentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CommentService"
	handlerType := (*douyincomment.CommentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CommentAction": kitex.NewMethodInfo(commentActionHandler, newCommentServiceCommentActionArgs, newCommentServiceCommentActionResult, false),
		"CommentList":   kitex.NewMethodInfo(commentListHandler, newCommentServiceCommentListArgs, newCommentServiceCommentListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "douyincomment",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func commentActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyincomment.CommentServiceCommentActionArgs)
	realResult := result.(*douyincomment.CommentServiceCommentActionResult)
	success, err := handler.(douyincomment.CommentService).CommentAction(ctx, realArg.Request, realArg.Uid)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceCommentActionArgs() interface{} {
	return douyincomment.NewCommentServiceCommentActionArgs()
}

func newCommentServiceCommentActionResult() interface{} {
	return douyincomment.NewCommentServiceCommentActionResult()
}

func commentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyincomment.CommentServiceCommentListArgs)
	realResult := result.(*douyincomment.CommentServiceCommentListResult)
	success, err := handler.(douyincomment.CommentService).CommentList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceCommentListArgs() interface{} {
	return douyincomment.NewCommentServiceCommentListArgs()
}

func newCommentServiceCommentListResult() interface{} {
	return douyincomment.NewCommentServiceCommentListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CommentAction(ctx context.Context, request *douyincomment.DouyinCommentActionRequest, uid int64) (r *douyincomment.DouyinCommentActionResponse, err error) {
	var _args douyincomment.CommentServiceCommentActionArgs
	_args.Request = request
	_args.Uid = uid
	var _result douyincomment.CommentServiceCommentActionResult
	if err = p.c.Call(ctx, "CommentAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentList(ctx context.Context, request *douyincomment.DouyinCommentListRequest) (r *douyincomment.DouyinCommentListResponse, err error) {
	var _args douyincomment.CommentServiceCommentListArgs
	_args.Request = request
	var _result douyincomment.CommentServiceCommentListResult
	if err = p.c.Call(ctx, "CommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
