// Code generated by hertz generator.

package main

import (
	"douyin/cmd/api/biz/mw"
	"douyin/cmd/api/biz/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzlogrus "github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
	"github.com/hertz-contrib/obs-opentelemetry/tracing"
)

func Init() {
	rpc.Init()
	mw.InitJWT()
	hlog.SetLevel(hlog.LevelInfo)
	hlog.SetLogger(hertzlogrus.NewLogger())
}

func main() {

	Init()
	tracer, cfg := tracing.NewServerTracer()

	h := server.New(
		server.WithHostPorts(":8080"),
		server.WithHandleMethodNotAllowed(true),
		tracer,
	)

	h.Use(tracing.ServerMiddleware(cfg))

	register(h)
	h.Spin()
}
