// Code generated by hertz generator.

package main

import (
	"douyin/cmd/api/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.StaticFile("/avatar.jpg", "../../pkg/static/pic.jpg")
	r.StaticFile("/myavatar.jpg", "../../pkg/static/mypic.jpg")
	r.StaticFile("/wall.jpg", "../../pkg/static/wall.jpg")
}
