// Code generated by hertz generator.

package main

import (
	"douyin/cmd/api/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.StaticFile("staticpic.jpg", "./static/staticpic.jpg")
}
