// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationservice

import (
	"context"
	douyinrelation "douyin/kitex_gen/douyinrelation"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return relationServiceServiceInfo
}

var relationServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "RelationService"
	handlerType := (*douyinrelation.RelationService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Action":          kitex.NewMethodInfo(actionHandler, newRelationServiceActionArgs, newRelationServiceActionResult, false),
		"FollowList":      kitex.NewMethodInfo(followListHandler, newRelationServiceFollowListArgs, newRelationServiceFollowListResult, false),
		"FollowerList":    kitex.NewMethodInfo(followerListHandler, newRelationServiceFollowerListArgs, newRelationServiceFollowerListResult, false),
		"FriendList":      kitex.NewMethodInfo(friendListHandler, newRelationServiceFriendListArgs, newRelationServiceFriendListResult, false),
		"GetRelationInfo": kitex.NewMethodInfo(getRelationInfoHandler, newRelationServiceGetRelationInfoArgs, newRelationServiceGetRelationInfoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "douyinrelation",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceActionArgs)
	realResult := result.(*douyinrelation.RelationServiceActionResult)
	success, err := handler.(douyinrelation.RelationService).Action(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceActionArgs() interface{} {
	return douyinrelation.NewRelationServiceActionArgs()
}

func newRelationServiceActionResult() interface{} {
	return douyinrelation.NewRelationServiceActionResult()
}

func followListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceFollowListArgs)
	realResult := result.(*douyinrelation.RelationServiceFollowListResult)
	success, err := handler.(douyinrelation.RelationService).FollowList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceFollowListArgs() interface{} {
	return douyinrelation.NewRelationServiceFollowListArgs()
}

func newRelationServiceFollowListResult() interface{} {
	return douyinrelation.NewRelationServiceFollowListResult()
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceFollowerListArgs)
	realResult := result.(*douyinrelation.RelationServiceFollowerListResult)
	success, err := handler.(douyinrelation.RelationService).FollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceFollowerListArgs() interface{} {
	return douyinrelation.NewRelationServiceFollowerListArgs()
}

func newRelationServiceFollowerListResult() interface{} {
	return douyinrelation.NewRelationServiceFollowerListResult()
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceFriendListArgs)
	realResult := result.(*douyinrelation.RelationServiceFriendListResult)
	success, err := handler.(douyinrelation.RelationService).FriendList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceFriendListArgs() interface{} {
	return douyinrelation.NewRelationServiceFriendListArgs()
}

func newRelationServiceFriendListResult() interface{} {
	return douyinrelation.NewRelationServiceFriendListResult()
}

func getRelationInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceGetRelationInfoArgs)
	realResult := result.(*douyinrelation.RelationServiceGetRelationInfoResult)
	success, err := handler.(douyinrelation.RelationService).GetRelationInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceGetRelationInfoArgs() interface{} {
	return douyinrelation.NewRelationServiceGetRelationInfoArgs()
}

func newRelationServiceGetRelationInfoResult() interface{} {
	return douyinrelation.NewRelationServiceGetRelationInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Action(ctx context.Context, req *douyinrelation.ActionRequest) (r *douyinrelation.ActionResponse, err error) {
	var _args douyinrelation.RelationServiceActionArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceActionResult
	if err = p.c.Call(ctx, "Action", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowList(ctx context.Context, req *douyinrelation.FollowListRequest) (r *douyinrelation.FollowListResponse, err error) {
	var _args douyinrelation.RelationServiceFollowListArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceFollowListResult
	if err = p.c.Call(ctx, "FollowList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, req *douyinrelation.FollowerListRequest) (r *douyinrelation.FollowerListResponse, err error) {
	var _args douyinrelation.RelationServiceFollowerListArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceFollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, req *douyinrelation.FriendListRequest) (r *douyinrelation.FriendListResponse, err error) {
	var _args douyinrelation.RelationServiceFriendListArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceFriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRelationInfo(ctx context.Context, req *douyinrelation.GetRelationInfoRequest) (r *douyinrelation.GetRelationInfoResponse, err error) {
	var _args douyinrelation.RelationServiceGetRelationInfoArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceGetRelationInfoResult
	if err = p.c.Call(ctx, "GetRelationInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
