// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationservice

import (
	"context"
	douyinrelation "douyin/kitex_gen/douyinrelation"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return relationServiceServiceInfo
}

var relationServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "RelationService"
	handlerType := (*douyinrelation.RelationService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Action":        kitex.NewMethodInfo(actionHandler, newRelationServiceActionArgs, newRelationServiceActionResult, false),
		"FollowList":    kitex.NewMethodInfo(followListHandler, newRelationServiceFollowListArgs, newRelationServiceFollowListResult, false),
		"FollowerList":  kitex.NewMethodInfo(followerListHandler, newRelationServiceFollowerListArgs, newRelationServiceFollowerListResult, false),
		"FriendList":    kitex.NewMethodInfo(friendListHandler, newRelationServiceFriendListArgs, newRelationServiceFriendListResult, false),
		"CountFollow":   kitex.NewMethodInfo(countFollowHandler, newRelationServiceCountFollowArgs, newRelationServiceCountFollowResult, false),
		"CountFollower": kitex.NewMethodInfo(countFollowerHandler, newRelationServiceCountFollowerArgs, newRelationServiceCountFollowerResult, false),
		"IsFollow":      kitex.NewMethodInfo(isFollowHandler, newRelationServiceIsFollowArgs, newRelationServiceIsFollowResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "douyinrelation",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceActionArgs)
	realResult := result.(*douyinrelation.RelationServiceActionResult)
	success, err := handler.(douyinrelation.RelationService).Action(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceActionArgs() interface{} {
	return douyinrelation.NewRelationServiceActionArgs()
}

func newRelationServiceActionResult() interface{} {
	return douyinrelation.NewRelationServiceActionResult()
}

func followListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceFollowListArgs)
	realResult := result.(*douyinrelation.RelationServiceFollowListResult)
	success, err := handler.(douyinrelation.RelationService).FollowList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceFollowListArgs() interface{} {
	return douyinrelation.NewRelationServiceFollowListArgs()
}

func newRelationServiceFollowListResult() interface{} {
	return douyinrelation.NewRelationServiceFollowListResult()
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceFollowerListArgs)
	realResult := result.(*douyinrelation.RelationServiceFollowerListResult)
	success, err := handler.(douyinrelation.RelationService).FollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceFollowerListArgs() interface{} {
	return douyinrelation.NewRelationServiceFollowerListArgs()
}

func newRelationServiceFollowerListResult() interface{} {
	return douyinrelation.NewRelationServiceFollowerListResult()
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceFriendListArgs)
	realResult := result.(*douyinrelation.RelationServiceFriendListResult)
	success, err := handler.(douyinrelation.RelationService).FriendList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceFriendListArgs() interface{} {
	return douyinrelation.NewRelationServiceFriendListArgs()
}

func newRelationServiceFriendListResult() interface{} {
	return douyinrelation.NewRelationServiceFriendListResult()
}

func countFollowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceCountFollowArgs)
	realResult := result.(*douyinrelation.RelationServiceCountFollowResult)
	success, err := handler.(douyinrelation.RelationService).CountFollow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceCountFollowArgs() interface{} {
	return douyinrelation.NewRelationServiceCountFollowArgs()
}

func newRelationServiceCountFollowResult() interface{} {
	return douyinrelation.NewRelationServiceCountFollowResult()
}

func countFollowerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceCountFollowerArgs)
	realResult := result.(*douyinrelation.RelationServiceCountFollowerResult)
	success, err := handler.(douyinrelation.RelationService).CountFollower(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceCountFollowerArgs() interface{} {
	return douyinrelation.NewRelationServiceCountFollowerArgs()
}

func newRelationServiceCountFollowerResult() interface{} {
	return douyinrelation.NewRelationServiceCountFollowerResult()
}

func isFollowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyinrelation.RelationServiceIsFollowArgs)
	realResult := result.(*douyinrelation.RelationServiceIsFollowResult)
	success, err := handler.(douyinrelation.RelationService).IsFollow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceIsFollowArgs() interface{} {
	return douyinrelation.NewRelationServiceIsFollowArgs()
}

func newRelationServiceIsFollowResult() interface{} {
	return douyinrelation.NewRelationServiceIsFollowResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Action(ctx context.Context, req *douyinrelation.ActionRequest) (r *douyinrelation.ActionResponse, err error) {
	var _args douyinrelation.RelationServiceActionArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceActionResult
	if err = p.c.Call(ctx, "Action", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowList(ctx context.Context, req *douyinrelation.FollowListRequest) (r *douyinrelation.FollowListResponse, err error) {
	var _args douyinrelation.RelationServiceFollowListArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceFollowListResult
	if err = p.c.Call(ctx, "FollowList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, req *douyinrelation.FollowerListRequest) (r *douyinrelation.FollowerListResponse, err error) {
	var _args douyinrelation.RelationServiceFollowerListArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceFollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, req *douyinrelation.FriendListRequest) (r *douyinrelation.FriendListResponse, err error) {
	var _args douyinrelation.RelationServiceFriendListArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceFriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountFollow(ctx context.Context, req *douyinrelation.CountFollowRequest) (r *douyinrelation.CountFollowResponse, err error) {
	var _args douyinrelation.RelationServiceCountFollowArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceCountFollowResult
	if err = p.c.Call(ctx, "CountFollow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountFollower(ctx context.Context, req *douyinrelation.CountFollowerRequest) (r *douyinrelation.CountFollowerResponse, err error) {
	var _args douyinrelation.RelationServiceCountFollowerArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceCountFollowerResult
	if err = p.c.Call(ctx, "CountFollower", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsFollow(ctx context.Context, req *douyinrelation.IsFollowRequest) (r *douyinrelation.IsFollowResponse, err error) {
	var _args douyinrelation.RelationServiceIsFollowArgs
	_args.Req = req
	var _result douyinrelation.RelationServiceIsFollowResult
	if err = p.c.Call(ctx, "IsFollow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
